<!DOCTYPE html>
<html>
    <head>
        <title>Property Details - {$model->Autogenerated_SDF_ID}</title>
        <link rel="stylesheet" href="{$helper->GetAssetPath('common/css/bootstrap.min.css')}" />
        <link rel="stylesheet" href="{$helper->GetAssetPath('fa/css/font-awesome.min.css')}" />
        <script type="text/javascript" src="{$helper->GetAssetPath('common/js/jquery-1.10.2.min.js')}"></script>
        <style type="text/css">
            .label-cell { font-weight: bolder; }
            body { overflow: auto; }
        </style>
        <script type="text/javascript">

            function getViewer() {
                return parent.parent;
            }

            function doPropertyUpdate() {
                var xml = "<UpdateOperation>";
                xml += "<Filter>Autogenerated_SDF_ID = {$model->Autogenerated_SDF_ID}</Filter>";
                xml += "<UpdateProperties>";
                var editedFields = $("input.form-control[data-edited=true]");
                for (var i = 0; i < editedFields.length; i++) {
                    var inputEl = $(editedFields[i]);
                    xml += "<Property><Name>" + inputEl.attr("name") + "</Name><Value>" + inputEl.val() + "</Value></Property>";
                }
                xml += "</UpdateProperties>";
                xml += "</UpdateOperation>";

                $("#btnSave").addClass("disabled");

                var updateUrl = window.location.href.replace(".html", ".xml");
                var promise = $.ajax({
                    method: "post",
                    url: updateUrl,
                    data: xml,
                    headers: {
                        "X-HTTP-Method-Override": "PUT"
                    },
                    success: onPropertyUpdated,
                    error: onPropertyUpdateError
                });
            }

            function onPropertyUpdateError(data, textStatus, jqXHR) {
                try {
                    var xml = data.responseXML;
                    var errNode = xml.getElementsByTagName("Error").item(0);
                    alert("Failed to update property.\n\n" + errNode.textContent);
                } catch (e) {
                    alert("Failed to update property");
                }
                $("#btnSave").removeClass("disabled");
            }

            function onPropertyUpdated(data, textStatus, jqXHR) {
                alert("Property Updated");
                $("#btnSave").removeClass("disabled");
                var map = getViewer().GetMapFrame();
                map.Refresh();
            }

            function editGeometry() {
                var viewer = getViewer();
                var map = viewer.GetMapFrame();
                map.DigitizePolygon(function(poly) {
                    var pairs = [];
                    for (var i = 0; i < poly.Count; i++) {
                        var pt = poly.Point(i);
                        pairs.push(pt.X + " " + pt.Y);
                    }
                    var geomWkt = "POLYGON ((" + pairs.join(", ") + "))";
                    var geomEl = $("#SHPGEOM");
                    geomEl.val(geomWkt);
                    markFieldDirty(geomEl);
                });
            }

            function markFieldDirty(el) {
                var elId = el.attr("id");
                el.attr("data-edited", true);
                var label = $("label[for='" + elId + "']");
                var labelText = label.text();
                if (labelText.indexOf(" (edited)") <= 0) {
                    labelText += " (edited)";
                    label.text(labelText);
                }
            }

            function onFormFieldChanged(e) {
                var el = $(e.target);
                markFieldDirty(el);
            }

            $(document).ready(function() {
                $("#editGeometry").on("click", editGeometry);
                $("input.form-control").change(onFormFieldChanged);
                $("#btnSave").on("click", doPropertyUpdate);
            });
        </script>
    </head>
    <body>
        <br/>
        <div class="container">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Property Details - {$model->Autogenerated_SDF_ID}
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label" for="RLDESCR1">Description1</label>
                        <input type="text" class="form-control input-sm" id="RLDESCR1" name="RLDESCR1" value="{$model->RLDESCR1}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RLDESCR2">Description2</label>
                        <input type="text" class="form-control input-sm" id="RLDESCR2" name="RLDESCR2" value="{$model->RLDESCR2}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RLDESCR3">Description3</label>
                        <input type="text" class="form-control input-sm" id="RLDESCR3" name="RLDESCR3" value="{$model->RLDESCR3}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RPROPAD">Property Address</label>
                        <input type="text" class="form-control input-sm" id="RPROPAD" name="RPROPAD" value="{$model->RPROPAD}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RTYPE">Zone</label>
                        <input type="text" class="form-control input-sm" id="RTYPE" name="RTYPE" value="{$model->RTYPE}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RACRE">Acreage</label>
                        <input type="text" class="form-control input-sm" id="RACRE" name="RACRE" value="{$model->RACRE}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RLOT">Lot Dimensions</label>
                        <input type="text" class="form-control input-sm" id="RLOT" name="RLOT" value="{$model->RLOT}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RNAME">Owner</label>
                        <input type="text" class="form-control input-sm" id="RNAME" name="RNAME" value="{$model->RNAME}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RBILAD">Billing Address</label>
                        <input type="text" class="form-control input-sm" id="RBILAD" name="RBILAD" value="{$model->RBILAD}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="RSQFT">Lot Size (sqft)</label>
                        <input type="text" class="form-control input-sm" id="RSQFT" name="RSQFT" value="{$model->RSQFT}" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="SHPGEOM">Geometry (WKT)</label>
                        <div class="input-group">
                            <input type="text" class="form-control input-sm" id="SHPGEOM" name="SHPGEOM" readonly="readonly" value="{$model->SHPGEOM}" />
                            <span class="input-group-btn">
                                <a title="Edit this geometry" class="btn btn-primary btn-sm btn-search" id="editGeometry"><i class="fa fa-edit"></i></a>
                            </span>
                        </div>
                    </div>
                    <button id="btnSave" class="btn btn-success">Save Changes</button>
                </div>
            </div>
        </div>
    </body>
</html>
