<!DOCTYPE html>
<html>
    <head>
        <title>Property Results</title>
        <link rel="stylesheet" href="{$helper->GetAssetPath('common/css/bootstrap.min.css')}" />
        <link rel="stylesheet" href="{$helper->GetAssetPath('fa/css/font-awesome.min.css')}" />
        <style type="text/css">
            #main { position: absolute; left: 0; top: 0; bottom: 0; right: 0; overflow-x: scroll; }
        </style>
        <script type="text/javascript">

            var zoomScale = 500;

            function getViewer() {
                return parent.parent;
            }

            function zoomToProperty(x, y) {
                getViewer().ZoomToView(x, y, zoomScale, true);
            }

            function updateQueryStringParameter(uri, key, value) {
                var re = new RegExp("([?|&])" + key + "=.*?(&|$)", "i");
                separator = uri.indexOf('?') !== -1 ? "&" : "?";
                if (uri.match(re)) {
                    return uri.replace(re, '$1' + key + "=" + value + '$2');
                } else {
                    return uri + separator + key + "=" + value;
                }
            }

            function gotoPage(pageNo) {
                window.location.href = updateQueryStringParameter(window.location.href, "page", pageNo);
            }

        </script>
    </head>
    <body>
        <!--
        Values for pagination debugging

        Current Page: {$currentPage}
        Max Pages: {$maxPages}
        End of Reader: {$endOfReader}
        -->
        <div id="main" class="container">
            <h3>Property Results</h3>
            {if $maxPages > 1}
                {if $currentPage > 1}
                <a class="pull-left" href="javascript:gotoPage({$currentPage - 1})">&lt;&lt;&nbsp;Previous Page&nbsp;&nbsp;</a>
                {/if}
                {if $currentPage < $maxPages}
                <a class="pull-left" href="javascript:gotoPage({$currentPage + 1})">Next Page&nbsp;&gt;&gt;</a>
                {/if}
            {elseif $maxPages = -1}
                {if $currentPage > 1}
                <a class="pull-left" href="javascript:gotoPage({$currentPage - 1})">&lt;&lt;&nbsp;Previous Page&nbsp;&nbsp;</a>
                {/if}
                <a class="pull-left" href="javascript:gotoPage({$currentPage + 1})">Next Page&nbsp;&gt;&gt;</a>
            {/if}
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>Address</th>
                        <th>Owner</th>
                        <th>Zone</th>
                        <th>Description1</th>
                        <th>Description2</th>
                        <th>Description3</th>
                        <th>City</th>
                        <th>Zip</th>
                    </tr>
                </thead>
                <tbody>
                    {while $model->Next()}
                    <tr>
                        <td><a class="btn btn-success" href="javascript:zoomToProperty({$model->Current()->GeometryAsType("SHPGEOM", "CentroidCommaSeparated")})"><i class="fa fa-search-plus"></i></a></td>
                        <td><a class="btn btn-primary" href="{$model->Current()->Autogenerated_SDF_ID}.html"><i class="fa fa-pencil"></i>&nbsp;{$model->Current()->Autogenerated_SDF_ID}</a></td>
                        <td>{$model->Current()->RPROPAD}</td>
                        <td>{$model->Current()->RNAME}</td>
                        <td>{$model->Current()->RTYPE}</td>
                        <td>{$model->Current()->RLDESCR1}</td>
                        <td>{$model->Current()->RLDESCR2}</td>
                        <td>{$model->Current()->RLDESCR3}</td>
                        <td>{$model->Current()->RCITY}</td>
                        <td>{$model->Current()->RZIP}</td>
                    </tr>
                    {/while}
                </tbody>
            </table>
            {if $maxPages > 1}
                {if $currentPage > 1}
                <a class="pull-left" href="javascript:gotoPage({$currentPage - 1})">&lt;&lt;&nbsp;Previous Page&nbsp;&nbsp;</a>
                {/if}
                {if $currentPage < $maxPages}
                <a class="pull-left" href="javascript:gotoPage({$currentPage + 1})">Next Page&nbsp;&gt;&gt;</a>
                {/if}
            {elseif $maxPages = -1}
                {if $currentPage > 1}
                <a class="pull-left" href="javascript:gotoPage({$currentPage - 1})">&lt;&lt;&nbsp;Previous Page&nbsp;&nbsp;</a>
                {/if}
                <a class="pull-left" href="javascript:gotoPage({$currentPage + 1})">Next Page&nbsp;&gt;&gt;</a>
            {/if}
        </div>
    </body>
</html>