<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:datetime="http://exslt.org/dates-and-times" xmlns:georss="http://www.georss.org/georss" version="2.0">
  <channel>
    <title>Property Feed</title>
    <link>/mapguide/rest/data/property/{$model->Autogenerated_SDF_ID}.georss</link>
    <description>GeoRSS Feed of Sheboygan properties</description>
    <language>en-us</language>
    <docs>https://github.com/jumpinjackie/mapguide-rest</docs>
    <generator>MapGuide REST Extension</generator>
  </channel>
  <item>
    <title>Property: {$model->Autogenerated_SDF_ID}</title>
    <link>/mapguide/rest/data/property/{$model->Autogenerated_SDF_ID}.html</link>
    <description>
      {$model->Autogenerated_SDF_ID}, {$model->RPROPAD}
    </description>
    {$model->GeometryAsType("SHPGEOM", "GeomRSSSimple")}
  </item>
</rss>