<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"
      xmlns:georss="http://www.georss.org/georss"
      xmlns:gml="http://www.opengis.net/gml">
  <title>Property atom view</title>
  {while $model->Next()}
  {assign var=property value=$model->Current()}
  <entry>
    <title>Property {$property->Autogenerated_SDF_ID}</title>
    <id>urn:uuid:{$property->Autogenerated_SDF_ID}</id>
    <link rel="alternate" type="application/atom+xml" href="/mapguide/rest/data/property/{$property->Autogenerated_SDF_ID}.atom" />
    <summary type="xhtml">
    <div xmlns="http://www.w3.org/1999/xhtml">
      <table>
        <tbody>
          <tr>
            <td>ID</td>
            <td>{$property->Autogenerated_SDF_ID}</td>
          </tr>
          <tr>
            <td>Address</td>
            <td>{$property->RPROPAD}</td>
          </tr>
        </tbody>
      </table>
    </div>
    </summary>
  </entry>
  {/while}
</feed>