<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Property - {$model->RPROPAD}</name>
    <Placemark>
      <name>{$model->RPROPAD}</name>
      <description><![CDATA[View property report for <a href="http://localhost/mapguide/rest/data/property/{$model->Autogenerated_SDF_ID}.html">{$model->RPROPAD}{$model->RBILAD}</a>]]></description>
      <snippet/>
      <styleUrl>{$helper->GetAssetPath("property/style_property_v1.kml")}#georest-property-style</styleUrl>
      <ExtendedData>
          <SchemaData schemaUrl="{$helper->GetAssetPath("property/schema_property_v1.kml")}#georest-property-schema">
            <SimpleData name="Autogenerated_SDF_ID">{$model->Autogenerated_SDF_ID}</SimpleData>
            <SimpleData name="RBILAD">{$model->RBILAD}</SimpleData>
          </SchemaData>
      </ExtendedData>
      {$model->GeometryAsType("SHPGEOM", "GeomKML")}    
      <atom:link href="http://localhost/mapguide/rest/data/property/{$model->Autogenerated_SDF_ID}.html" />
    </Placemark>
    <atom:author>      
      <atom:name>mapguide-rest Sample Data</atom:name>    
      <atom:uri>https://github.com/jumpinjackie/mapguide-rest</atom:uri>    
    </atom:author>    
  </Document> 
</kml>