<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:datetime="http://exslt.org/dates-and-times" xmlns:georss="http://www.georss.org/georss" version="2.0">
  <channel>
    <title>Property Feed</title>
    <link>/mapguide/rest/data/property/.georss</link>
    <description>GeoRSS Feed of Sheboygan properties</description>
    <language>en-us</language>
    <docs>https://github.com/jumpinjackie/mapguide-rest</docs>
    <generator>MapGuide REST Extension</generator>
  </channel>
  {while $model->Next()}
  {assign var=property value=$model->Current()}
  <item>
    <title>Property: {$property->Autogenerated_SDF_ID}</title>
    <link>/mapguide/rest/data/property/{$property->Autogenerated_SDF_ID}.html</link>
    <description>
      {$property->Autogenerated_SDF_ID}, {$property->RPROPAD}
    </description>
    {$property->GeometryAsType("SHPGEOM", "GeomRSSSimple")}
  </item>
  {/while}
</rss>