<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Sheboygan Properties</name>
    <open>1</open>
    <Folder>
      <name>Properties in View</name>
      <open>1</open>
      {while $model->Next()}
      <Placemark>
        <name>{$model->Current()->Autogenerated_SDF_ID}: {$model->Current()->RPROPAD}</name>
        <description><![CDATA[View property report for <a href="http://localhost/mapguide/rest/data/property/{$model->Current()->Autogenerated_SDF_ID}.html">{$model->Current()->RPROPAD}</a>]]></description>
        <snippet/>
        <styleUrl>{$helper->GetAssetPath("property/style_property_v1.kml")}#georest-property-style</styleUrl>
        <ExtendedData>
          <SchemaData schemaUrl="{$helper->GetAssetPath("property/schema_property_v1.kml")}#georest-property-schema">
            <SimpleData name="Autogenerated_SDF_ID">{$model->Current()->Autogenerated_SDF_ID}</SimpleData>
            <SimpleData name="RBILAD">{$model->Current()->RBILAD}</SimpleData>
          </SchemaData>
        </ExtendedData>
        <snippet/>
        {$model->Current()->GeometryAsType("SHPGEOM", "GeomKML")}
      </Placemark>
      {/while}
    </Folder>
    <atom:author>      
      <atom:name>mapguide-rest Sample Data</atom:name>    
      <atom:uri>https://github.com/jumpinjackie/mapguide-rest</atom:uri>    
    </atom:author>
  </Document> 
</kml>
