<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"
      xmlns:georss="http://www.georss.org/georss"
      xmlns:gml="http://www.opengis.net/gml">
  <title>Property atom view</title>
  <entry>
    <title>Property {$model->Autogenerated_SDF_ID}</title>
    <id>urn:uuid:{$model->Autogenerated_SDF_ID}</id>
    <link rel="alternate" type="text/html" href="/mapguide/rest/data/property/{$model->Autogenerated_SDF_ID}.html" />
    <summary type="xhtml">
    <div xmlns="http://www.w3.org/1999/xhtml">
      <table>
        <tbody>
          <tr>
            <td>ID</td>
            <td>{$model->Autogenerated_SDF_ID}</td>
          </tr>
          <tr>
            <td>Address</td>
            <td>{$model->RPROPAD}</td>
          </tr>
        </tbody>
      </table>
    </div>
    </summary>
  </entry>
</feed>