<!DOCTYPE html>
<html>
    <head>
        <title>Property Report - {$model->RPROPAD}</title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
        <style type="text/css">
            .label-cell { font-weight: bolder; }
        </style>
    </head>
    <body>
        <div class="container">
            <h3>Property Report - {$model->RPROPAD}</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            Property Details
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped table-bordered">
                                <tbody>
                                    <tr>
                                        <td class="label-cell">ID</td>
                                        <td>{$model->Autogenerated_SDF_ID}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Description1</td>
                                        <td>{$model->RLDESCR1}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Description2</td>
                                        <td>{$model->RLDESCR2}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Description3</td>
                                        <td>{$model->RLDESCR3}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Zone</td>
                                        <td>{$model->RTYPE}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Acreage</td>
                                        <td>{$model->RACRE}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Lot Dimensions</td>
                                        <td>{$model->RLOT}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Owner</td>
                                        <td>{$model->RNAME}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Billing Address</td>
                                        <td>{$model->RBILAD}</td>
                                    </tr>
                                    <tr>
                                        <td class="label-cell">Lot Size (sqft)</td>
                                        <td>{$model->RSQFT}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Image</div>
                        <div class="panel-body">
                            <img src="{$model->Autogenerated_SDF_ID}.png" />
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">Other Formats</div>
                        <div class="panel-body">
                            <a href="{$model->Autogenerated_SDF_ID}.xml">XML</a>
                            <a href="{$model->Autogenerated_SDF_ID}.geojson">GeoJSON</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
