<html>
    <head>
        <title>Property Results</title>
    </head>
    <body>
        <h1>Property Results</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Address</th>
                    <th>Owner</th>
                </tr>
            </thead>
            <tbody>
                {while $model->Next()}
                <tr>
                    <td><a href="{$model->Current()->Autogenerated_SDF_ID}.html">{$model->Current()->Autogenerated_SDF_ID}</a></td>
                    <td>{$model->Current()->RPROPAD}</td>
                    <td>{$model->Current()->RNAME}</td>
                </tr>
                {/while}
            </tbody>
        </table>
    </body>
</html>