<html>
    <head>
        <title>Property Details - {$model->RPROPAD}</title>
    </head>
    <body>
        <h1>Property Details - {$model->RPROPAD}</h1>
        <img src="{$model->Autogenerated_SDF_ID}.png" />
        <table>
            <tbody>
                <tr>
                    <td>ID</td>
                    <td>{$model->Autogenerated_SDF_ID}</td>
                </tr>
                <tr>
                    <td>Description1</td>
                    <td>{$model->RLDESCR1}</td>
                </tr>
                <tr>
                    <td>Description2</td>
                    <td>{$model->RLDESCR2}</td>
                </tr>
                <tr>
                    <td>Description3</td>
                    <td>{$model->RLDESCR3}</td>
                </tr>
                <tr>
                    <td>Zone</td>
                    <td>{$model->RTYPE}</td>
                </tr>
                <tr>
                    <td>Acreage</td>
                    <td>{$model->RACRE}</td>
                </tr>
                <tr>
                    <td>Lot Dimensions</td>
                    <td>{$model->RLOT}</td>
                </tr>
                <tr>
                    <td>Owner</td>
                    <td>{$model->RNAME}</td>
                </tr>
                <tr>
                    <td>Billing Address</td>
                    <td>{$model->RBILAD}</td>
                </tr>
                <tr>
                    <td>Lot Size (sqft)</td>
                    <td>{$model->RSQFT}</td>
                </tr>
            </tbody>
        </table>
    </body>
</html>