<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Sheboygan Properties</name>
    <open>1</open>
    <Folder>
      <name>Properties in View</name>
      <open>1</open>
      {while $model->Next()}
      <Placemark>
        <name>{$model->Current()->Autogenerated_SDF_ID}: {$model->Current()->RBILAD}</name>
        <snippet/>
        {$model->Current()->GeometryAsType("SHPGEOM", "GeomKML")}
      </Placemark>
      {/while}
    </Folder>
  </Document> 
</kml>
