<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Property - {$model->RPROPAD}</name>
    <Placemark>
      <name>{$model->Autogenerated_SDF_ID}: {$model->RPROPAD}</name>
      <snippet/>
      {$model->GeometryAsType("SHPGEOM", "GeomKML")}
    </Placemark>
  </Document> 
</kml>