<!DOCTYPE html>
<html>
    <head>
        <title>Property Results</title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <h3>Property Results</h3>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Address</th>
                        <th>Owner</th>
                        <th>Zone</th>
                        <th>Description1</th>
                        <th>Description2</th>
                        <th>Description3</th>
                        <th>City</th>
                        <th>Zip</th>
                    </tr>
                </thead>
                <tbody>
                    {while $model->Next()}
                    <tr>
                        <td><a href="{$model->Current()->Autogenerated_SDF_ID}.html">{$model->Current()->Autogenerated_SDF_ID}</a></td>
                        <td>{$model->Current()->RPROPAD}</td>
                        <td>{$model->Current()->RNAME}</td>
                        <td>{$model->Current()->RTYPE}</td>
                        <td>{$model->Current()->RLDESCR1}</td>
                        <td>{$model->Current()->RLDESCR2}</td>
                        <td>{$model->Current()->RLDESCR3}</td>
                        <td>{$model->Current()->RCITY}</td>
                        <td>{$model->Current()->RZIP}</td>
                    </tr>
                    {/while}
                </tbody>
            </table>
        </div>
    </body>
</html>