<?php

//
//  Copyright (C) 2014 by Jackie Ng
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of version 2.1 of the GNU Lesser
//  General Public License as published by the Free Software Foundation.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// These are helper routes to help play nice with the Swagger UI
//
// API Docs are regenerated by issuing the following command:
// php vendor\zircote\swagger-php\bin\swagger "%CD%\app\routes" -o "%CD%\doc" --default-base-path http://localhost/mapguide/rest
//
// TODO: We should try to dynamically build this at runtime so that the base path can be inferred instead of specified up-front

$app->get("/apidoc/", function() use ($app) {
    $path = $app->config("AppRootDir")."/doc/api-docs.json";
    $app->response->header("Content-Type", "application/json");
    $app->response->setBody(file_get_contents($path));
});
$app->get("/apidoc/:file", function($file) use ($app) {
    $path = $app->config("AppRootDir")."/doc/$file";
    $app->response->header("Content-Type", "application/json");
    $app->response->setBody(file_get_contents($path));
});

?>