<?php

//
//  Copyright (C) 2016 by Jackie Ng
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of version 2.1 of the GNU Lesser
//  General Public License as published by the Free Software Foundation.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

require_once dirname(__FILE__)."/../Config.php";
require_once dirname(__FILE__)."/../ServiceTest.php";

class EnumerateResourceReferencesApiTest extends ServiceTest {
    private function getCreateXml() {
        $fsXml = "<FeatureSourceParams>";
            $fsXml .= "<File>";
                $fsXml .= "<Provider>OSGeo.SDF</Provider>";
                $fsXml .= "<FileName>Test.sdf</FileName>";
            $fsXml .= "</File>";
            $fsXml .= "<SpatialContext>";
                $fsXml .= "<Name>Default</Name>";
                $fsXml .= "<Description>Default Spatial Context</Description>";
                $fsXml .= "<CoordinateSystem>LL84</CoordinateSystem>";
                $fsXml .= "<XYTolerance>0.00001</XYTolerance>";
                $fsXml .= "<ZTolerance>0.00001</ZTolerance>";
            $fsXml .= "</SpatialContext>";
            $fsXml .= "<FeatureSchema>";
                $fsXml .= "<Name>Default</Name>";
                $fsXml .= "<Description>Default Feature Schema</Description>";
                $fsXml .= "<ClassDefinition>";
                    $fsXml .= "<Name>Class1</Name>";
                    $fsXml .= "<Description>First feature class</Description>";
                    $fsXml .= "<DefaultGeometryPropertyName>Geometry</DefaultGeometryPropertyName>";
                    $fsXml .= "<PropertyDefinition>";
                        $fsXml .= "<Name>ID</Name>";
                        $fsXml .= "<Description>Autogenerated ID property</Description>";
                        $fsXml .= "<PropertyType>100</PropertyType>";
                        $fsXml .= "<IsIdentity>true</IsIdentity>";
                        $fsXml .= "<DataType>7</DataType>";
                        $fsXml .= "<Nullable>false</Nullable>";
                        $fsXml .= "<ReadOnly>false</ReadOnly>";
                        $fsXml .= "<IsAutoGenerated>true</IsAutoGenerated>";
                    $fsXml .= "</PropertyDefinition>";
                    $fsXml .= "<PropertyDefinition>";
                        $fsXml .= "<Name>Geometry</Name>";
                        $fsXml .= "<Description>Geometry Property</Description>";
                        $fsXml .= "<PropertyType>102</PropertyType>";
                        $fsXml .= "<GeometryTypes>4</GeometryTypes>";
                        $fsXml .= "<HasElevation>false</HasElevation>";
                        $fsXml .= "<HasMeasure>false</HasMeasure>";
                        $fsXml .= "<ReadOnly>false</ReadOnly>";
                        $fsXml .= "<SpatialContextAssociation>Default</SpatialContextAssociation>";
                    $fsXml .= "</PropertyDefinition>";
                $fsXml .= "</ClassDefinition>";
            $fsXml .= "</FeatureSchema>";
        $fsXml .= "</FeatureSourceParams>";

        return $fsXml;
    }
    private function getCreateJson() {
        $fsJson = "{\"FeatureSourceParams\":{\"@xmlns:xsi\":\"http://www.w3.org/2001/XMLSchema-instance\",\"File\":{\"Provider\":\"OSGeo.SDF\",\"FileName\":\"Test.sdf\"},\"SpatialContext\":{\"Name\":\"Default\",\"Description\":\"Default Spatial Context\",\"CoordinateSystem\":\"LL84\",\"XYTolerance\":\"0.00001\",\"ZTolerance\":\"0.00001\"},\"FeatureSchema\":{\"Name\":\"Default\",\"Description\":\"Default Feature Schema\",\"ClassDefinition\":[{\"Name\":\"Class1\",\"Description\":\"First feature class\",\"DefaultGeometryPropertyName\":\"Geometry\",\"PropertyDefinition\":[{\"Name\":\"ID\",\"Description\":\"Autogenerated ID property\",\"PropertyType\":\"100\",\"IsIdentity\":\"true\",\"DataType\":\"7\",\"Nullable\":\"false\",\"ReadOnly\":\"false\",\"IsAutoGenerated\":\"true\"},{\"Name\":\"Geometry\",\"Description\":\"Geometry Property\",\"PropertyType\":\"102\",\"GeometryTypes\":\"4\",\"HasElevation\":\"false\",\"HasMeasure\":\"false\",\"ReadOnly\":\"false\",\"SpatialContextAssociation\":\"Default\"}]}]}}}";

        return $fsJson;
    }
    public function testOperation() {
        $resp = $this->apiTestAnon("/session/".$this->anonymousSessionId."/CreateXml.FeatureSource/xml", "POST", $this->getCreateXml());
        $this->assertStatusCodeIs(200, $resp);

        $resp = $this->apiTestAnon("/session/".$this->anonymousSessionId."/CreateJson.FeatureSource/json", "POST", $this->getCreateJson());
        $this->assertStatusCodeIs(200, $resp);
    }
}