@endpoint_domain = http://localhost:8018
@endpoint_base = {{endpoint_domain}}/mapguide/rest
@admin_user = Administrator
@admin_pass = admin
@default_content_type = json
@default_content_mime = application/json